# Generated by Django 4.0.10 on 2024-05-19 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('WISHLIST', 'Wishlist'), ('APPLIED', 'Applied'), ('INTERVIEW', 'Interview'), ('REJECTED', 'Rejected'), ('OFFER', 'Offer'), ('DORMANT', 'Dormant'), ('FOLLOW_UP', 'Follow Up')], default='WISHLIST', max_length=200)),
                ('link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('tech_stacks', models.ManyToManyField(to='jobs.techstack')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
