# Generated by Django 4.0.10 on 2024-07-06 09:05

from django.db import migrations, models
import django.utils.timezone
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobsource_job_job_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobsource',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='jobsource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobsource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobsource',
            name='link_regex',
            field=models.CharField(blank=True, max_length=500, validators=[jobs.validators.valid_regex]),
        ),
    ]
