# Generated by Django 4.0.10 on 2024-07-30 19:27

from django.conf import settings
from django.db import migrations, models
from django.contrib.auth import get_user_model
import django.db.models.deletion


def set_job_created_by(apps, schema):
    User = get_user_model()
    Job = apps.get_model("jobs", "Job")
    default_user, _ = User.objects.get_or_create(username="admin")
    orphan_jobs = Job.objects.filter(created_by=None)

    orphan_jobs.update(created_by=default_user)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0004_alter_techstack_options_alter_techstack_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_job_created_by, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        )
    ]
