# Generated by Django 4.0.10 on 2024-08-14 13:56

from django.db import migrations, models
import django.db.models.deletion


def set_job_source_on_jobs(apps, schema):
    Job = apps.get_model('jobs', "Job")
    JobSource = apps.get_model('jobs', "JobSource")

    default_job_source, _ = JobSource.objects.get_or_create(name="default")
    jobs_without_job_source = Job.objects.filter(job_source__isnull=True)

    jobs_without_job_source.update(job_source=default_job_source)


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_created_by_alter_job_job_source_and_more'),
    ]

    operations = [
        migrations.RunPython(set_job_source_on_jobs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='job',
            name='job_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.jobsource'),
        ),
    ]
