# Generated by Django 4.0.10 on 2024-08-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_add_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expired_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
