# Generated by Django 4.0.10 on 2024-08-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_add_job_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('WISHLIST', 'Wishlist'), ('APPLIED', 'Applied'), ('INTERVIEW', 'Interview'), ('REJECTED', 'Rejected'), ('OFFER', 'Offer'), ('DORMANT', 'Dormant'), ('FOLLOW_UP', 'Follow Up'), ('EXPIRED', 'Expired')], default='WISHLIST', max_length=200),
        ),
    ]
