services:
  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - python_packages:/usr/local/lib/python3.10/site-packages
    depends_on:
      - db
    environment:
      - USE_DOCKER=True
      - DJANGO_DEBUG=True
      - DJANGO_SETTINGS_MODULE=job_tracker.settings.local
      - DJANGO_SECRET_KEY=django-insecure-rq-8dkoe-p))lzvpn7!c*k)l!6jh^#mjvdn14n*jh&fsli7=+7
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: job-tracker
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  python_packages:
