# ==== Black ====
# Full list of configuration options available here: https://black.readthedocs.io/en/stable/usage_and_configuration/
[tool.black]
line-length = 119
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
    .+/migrations
)/
'''

# ==== isort ====
# Full list of configuration options available here: https://pycqa.github.io/isort/docs/configuration/options.html
[tool.isort]
profile = "black"
line_length = 119
known_first_party = [
    "job_tracker"
]
skip = ["venv/"]
skip_glob = ["**/migrations/*.py"]

# ==== djlint ====
# Full list of configuration options available here: https://www.djlint.com/docs/linter/
[tool.djlint]
profile = "django"
ignore = "H031,H030"
