# Generated by Django 4.0.10 on 2024-07-30 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_create_activities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='activitytype',
            options={'verbose_name_plural': 'Activity Types'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.PROTECT, to='activities.activitytype', to_field='name'),
        ),
    ]
